# Generated by Django 3.2.13 on 2022-07-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification_delay',
            field=models.IntegerField(default=5),
        ),
    ]
