# Generated by Django 3.2.13 on 2022-07-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_notification_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.TextField(default='adult'),
        ),
    ]
