# Generated by Django 3.2.13 on 2022-07-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='emissions',
            field=models.FloatField(default=0.0),
        ),
    ]
