# Generated by Django 4.0.5 on 2022-06-30 15:43
# flake8: noqa
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_now_add=True)),
                ('temp', models.FloatField(default=0.0)),
                ('min_temp', models.FloatField(default=0.0)),
                ('max_temp', models.FloatField(default=0.0)),
                ('humidity', models.IntegerField(default=0)),
                ('weather_main', models.CharField(max_length=50)),
                ('weather_description', models.CharField(max_length=255)),
                ('weather_icon', models.CharField(max_length=255)),
                ('clouds', models.IntegerField(default=0)),
                ('pop', models.FloatField(default=0.0)),
            ],
        ),
    ]
