# Generated by Django 4.0.5 on 2022-06-30 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='weather_icon',
            new_name='weather_icon_id',
        ),
    ]
