# Generated by Django 4.0.5 on 2022-06-30 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_rename_weather_icon_book_weather_icon_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='weather_icon_id',
            new_name='weather_icon',
        ),
    ]
