# Generated by Django 4.0.5 on 2022-06-30 16:20
# flake8: noqa
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_rename_weather_icon_id_book_weather_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='max_temp',
            new_name='temp_max',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='min_temp',
            new_name='temp_min',
        ),
    ]
