# Generated by Django 4.0.5 on 2022-07-01 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_rename_max_temp_book_temp_max_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Forecast',
        ),
    ]
