# Generated by Django 4.0.5 on 2022-07-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_rename_book_forecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='dt_txt',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='dt',
            field=models.BigIntegerField(),
        ),
    ]
