# Generated by Django 4.0.5 on 2022-07-08 14:28
# flake8: noqa
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_forecast_dt_txt_alter_forecast_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.BigIntegerField()),
                ('weather_id', models.IntegerField()),
                ('weather_main', models.CharField(max_length=50)),
                ('weather_description', models.CharField(max_length=255)),
                ('weather_icon', models.CharField(max_length=255)),
                ('main_temp', models.FloatField(default=0.0)),
                ('main_temp_min', models.FloatField(default=0.0)),
                ('main_temp_max', models.FloatField(default=0.0)),
                ('humidity', models.IntegerField(default=0)),
                ('wind_speed', models.FloatField(default=0.0)),
                ('clouds', models.IntegerField(default=0)),
                ('rain_1h', models.FloatField(default=0.0)),
                ('rain_3h', models.FloatField(default=0.0)),
            ],
        ),
    ]
