# Generated by Django 4.0.5 on 2022-07-08 14:42
# flake8: noqa
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_weather'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weather',
            new_name='CurrentWeather',
        ),
    ]
