# Generated by Django 4.0.5 on 2022-07-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_rename_weather_currentweather'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='wind_speed',
            field=models.FloatField(default=0.0),
        ),
    ]
